services:
  mongodb:
    image: mongo:7.0.8
    container_name: skillq-mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: skillqUser
      MONGO_INITDB_ROOT_PASSWORD: skillqPassword
      MONGO_INITDB_DATABASE: skillqdb
      MONGO_INITDB_USER: skillqUser
      MONGO_INITDB_PASSWORD: skillqPassword
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:7.2.4
    container_name: skillq-redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  minio:
    image: minio/minio:RELEASE.2024-05-01T01-11-10Z
    container_name: skillq-minio
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - MINIO_COMPRESS=on

  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    container_name: skillq-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - skillq-network
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  mongodb:
  redis:
  minio:
  rabbitmq:

networks:
  skillq-network:
