// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package userapp

import (
	"github.com/BrianLusina/skillq/server/app/di"
	"github.com/BrianLusina/skillq/server/app/internal/database/repositories/userrepo"
	"github.com/BrianLusina/skillq/server/app/internal/database/repositories/userverification"
	"github.com/BrianLusina/skillq/server/app/internal/domain/services/usersvc"
	"github.com/BrianLusina/skillq/server/infra/logger"
	"github.com/BrianLusina/skillq/server/infra/messaging/amqp"
	"github.com/BrianLusina/skillq/server/infra/messaging/amqp/consumer"
	"github.com/BrianLusina/skillq/server/infra/messaging/amqp/publisher"
	"github.com/BrianLusina/skillq/server/infra/mongodb"
	"github.com/BrianLusina/skillq/server/infra/storage/minio"
)

// Injectors from wire.go:

// InitApp initializes the user application
func InitApp(mongodbConfig mongodb.MongoDBConfig, amqpConfig amqp.Config, minioConfig minio.Config) (*UserApp, error) {
	loggerLogger := logger.New()
	mongoDBClient := di.ProvideUserMongoDbClient(mongodbConfig)
	amqpClient, err := amqp.NewAmqpClient(amqpConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	amqpEventPublisher, err := amqppublisher.NewPublisher(amqpClient, loggerLogger)
	if err != nil {
		return nil, err
	}
	amqpEventConsumer, err := amqpconsumer.NewConsumer(amqpClient, loggerLogger)
	if err != nil {
		return nil, err
	}
	storageClient, err := minio.NewClient(minioConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	userRepoPort := userrepo.New(mongoDBClient)
	userService := usersvc.New(userRepoPort, amqpEventPublisher, storageClient)
	mongodbMongoDBClient := di.ProvideUserVerificationMongoDbClient(mongodbConfig)
	userVerificationRepoPort := userverificationrepo.New(mongodbMongoDBClient)
	userVerificationService := usersvc.NewVerification(userService, userVerificationRepoPort, amqpEventPublisher)
	eventHandler := di.ProvideEmailVerificationSentEventHandler(userVerificationService, amqpEventPublisher)
	handlersEventHandler := di.ProvideEmailVerificationStartedEventHandler(userVerificationService, amqpEventPublisher)
	eventHandler2 := di.ProvideStoreImageTaskHandler(storageClient, userRepoPort, amqpEventPublisher)
	userApp := New(mongodbConfig, amqpConfig, minioConfig, loggerLogger, mongoDBClient, amqpClient, amqpEventPublisher, amqpEventConsumer, storageClient, userRepoPort, userService, eventHandler, handlersEventHandler, eventHandler2)
	return userApp, nil
}
