name: Test

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  test:
    strategy:
      matrix:
        go-version: [ '1.22' ]
    name: Test
    uses: SanctumLabs/ci-workflows/.github/workflows/go-test.yml@main
    with:
      go-version: ${{ matrix.go-version }}
      command: make test-coverage
